DNA_TO_AMINO_ACID = {"GCA": "A", "GCC": "A", "GCG": "A", "GCT": "A",
                     "AAC": "B", "AAT": "B", "GAC": "B", "GAT": "B",
                     "TGC": "C", "TGT": "C",
                     # "GAC":"D", "GAT":"D",
                     "GAA": "E", "GAG": "E",
                     "TTC": "F", "TTT": "F",
                     "GGA": "G", "GGC": "G", "GGG": "G", "GGT": "G",
                     "CAC": "H", "CAT": "H",
                     "ATA": "I", "ATC": "I", "ATT": "I",
                     "AAA": "K", "AAG": "K",
                     "CTA": "L", "CTC": "L", "CTG": "L", "CTT": "L", "TTA": "L", "TTG": "L",
                     "ATG": "M",
                     # "AAC":"N","AAT":"N",
                     "CCA": "P", "CCC": "P", "CCG": "P", "CCT": "P",
                     "CAA": "Q", "CAG": "Q",
                     "AGA": "R", "AGG": "R", "CGA": "R", "CGC": "R", "CGG": "R", "CGT": "R",
                     "AGC": "S", "AGT": "S", "TCA": "S", "TCC": "S", "TCG": "S", "TCT": "S",
                     "ACA": "T", "ACC": "T", "ACG": "T", "ACT": "T",
                     "GTA": "V", "GTC": "V", "GTG": "V", "GTT": "V",
                     "TGG": "W",
                     "NNN": "X",
                     "TAC": "Y", "TAT": "Y",
                     # "CAA":"Z","CAG":"Z","GAA":"Z","GAG":"Z",
                     "TAA": "*", "TAG": "*", "TGA": "*"}

AMINO_ACID_TO_DNA = {
    "A": ["GCA", "GCC", "GCG", "GCT"],
    "B": ["AAC", "AAT", "GAC", "GAT"],
    "C": ["TGC", "TGT"],
    # "D": ["GAC", "GAT"],
    "E": ["GAA", "GAG"],
    "F": ["TTC", "TTT"],
    "G": ["GGA", "GGC", "GGG", "GGT"],
    "H": ["CAC", "CAT"],
    "I": ["ATA", "ATC", "ATT"],
    "K": ["AAA", "AAG"],
    "L": ["CTA", "CTC", "CTG", "CTT", "TTA", "TTG"],
    "M": ["ATG"],
    # "N": ["AAC","AAT"],
    "P": ["CCA", "CCC", "CCG", "CCT"],
    "Q": ["CAA", "CAG"],
    "R": ["AGA", "AGG", "CGA", "CGC", "CGG", "CGT"],
    "S": ["AGC", "AGT", "TCA", "TCC", "TCG", "TCT"],
    "T": ["ACA", "ACC", "ACG", "ACT"],
    "V": ["GTA", "GTC", "GTG", "GTT"],
    "W": ["TGG"],
    "X": ["NNN"],
    "Y": ["TAC", "TAT"],
    # "Z": ["CAA","CAG","GAA","GAG"]
    "*": ["TAA", "TAG", "TGA"]
}
